"""
PDF Report Generation Service
Generates various business reports in PDF format
"""
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from io import BytesIO
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from app.models.product import Product
import os

class ReportService:
    
    @staticmethod
    def generate_sales_report(db: Session, merchant_id: str, days: int = 30):
        """Generate sales report for last N days"""
        buffer = BytesIO()
        p = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        
        # Header
        p.setFont("Helvetica-Bold", 16)
        p.drawString(2*cm, height - 2*cm, "LAPORAN PENJUALAN")
        
        p.setFont("Helvetica", 10)
        p.drawString(2*cm, height - 3*cm, f"Periode: {days} hari terakhir")
        p.drawString(2*cm, height - 3.5*cm, f"Tanggal: {datetime.now().strftime('%d/%m/%Y %H:%M')}")
        
       # Note: Transaction data would come from MySQL via Go backend
        # This is simplified for demo
        p.setFont("Helvetica", 10)
        p.drawString(2*cm, height - 5*cm, "Ringkasan Penjualan:")
        p.drawString(2*cm, height - 6*cm, "Total Transaksi: - (data dari Go backend)")
        p.drawString(2*cm, height - 6.5*cm, "Total Pendapatan: - (data dari Go backend)")
        
        # Footer
        p.setFont("Helvetica-Oblique", 8)
        p.drawString(2*cm, 2*cm, f"Generated by Smartgement AI - {datetime.now().strftime('%Y')}")
        
        p.save()
        return buffer.getvalue()
    
    @staticmethod
    def generate_inventory_report(db: Session, merchant_id: str):
        """Generate product inventory report"""
        buffer = BytesIO()
        p = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        
        # Header
        p.setFont("Helvetica-Bold", 16)
        p.drawString(2*cm, height - 2*cm, "LAPORAN INVENTORI PRODUK")
        
        p.setFont("Helvetica", 10)
        p.drawString(2*cm, height - 3*cm, f"Tanggal: {datetime.now().strftime('%d/%m/%Y %H:%M')}")
        
        # Get products
        products = db.query(Product).filter(Product.merchant_id == merchant_id).all()
        
        y = height - 5*cm
        p.setFont("Helvetica-Bold", 10)
        p.drawString(2*cm, y, "Produk")
        p.drawString(10*cm, y, "Stok")
        p.drawString(13*cm, y, "Harga")
        p.drawString(16*cm, y, "Total Nilai")
        
        y -= 0.7*cm
        p.setFont("Helvetica", 9)
        
        total_value = 0
        for product in products[:20]:  # Limit to 20 products for first page
            p.drawString(2*cm, y, product.name[:30])
            p.drawString(10*cm, y, str(product.stock))
            p.drawString(13*cm, y, f"Rp{product.price:,.0f}")
            value = product.stock * product.price
            total_value += value
            p.drawString(16*cm, y, f"Rp{value:,.0f}")
            y -= 0.5*cm
            
            if y < 3*cm:
                break
        
        # Summary
        y -= 1*cm
        p.setFont("Helvetica-Bold", 10)
        p.drawString(13*cm, y, "TOTAL:")
        p.drawString(16*cm, y, f"Rp{total_value:,.0f}")
        
        # Footer
        p.setFont("Helvetica-Oblique", 8)
        p.drawString(2*cm, 2*cm, f"Generated by Smartgement AI - {datetime.now().strftime('%Y')}")
        
        p.save()
        return buffer.getvalue()
    
    @staticmethod
    def generate_summary_report(db: Session, merchant_id: str):
        """Generate business summary report"""
        buffer = BytesIO()
        p = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        
        # Header
        p.setFont("Helvetica-Bold", 16)
        p.drawString(2*cm, height - 2*cm, "RINGKASAN BISNIS")
        
        p.setFont("Helvetica", 10)
        p.drawString(2*cm, height - 3*cm, f"Tanggal: {datetime.now().strftime('%d/%m/%Y %H:%M')}")
        
        # Get summary data
        products = db.query(Product).filter(Product.merchant_id == merchant_id).all()
        total_products = len(products)
        total_stock = sum(p.stock for p in products)
        total_value = sum(p.stock * p.price for p in products)
        
        y = height - 5*cm
        p.setFont("Helvetica", 11)
        p.drawString(2*cm, y, f"📦 Total Produk: {total_products}")
        y -= 1*cm
        p.drawString(2*cm, y, f"📊 Total Stok: {total_stock} unit")
        y -= 1*cm
        p.drawString(2*cm, y, f"💰 Total Nilai Inventori: Rp{total_value:,.0f}")
        
        # Low stock alert
        y -= 2*cm
        p.setFont("Helvetica-Bold", 11)
        p.drawString(2*cm, y, "⚠️ Produk Stok Rendah:")
        y -= 0.7*cm
        
        p.setFont("Helvetica", 10)
        low_stock = [p for p in products if p.stock < 10]
        if low_stock:
            for product in low_stock[:10]:
                p.drawString(2.5*cm, y, f"• {product.name}: {product.stock} unit")
                y -= 0.5*cm
        else:
            p.drawString(2.5*cm, y, "Tidak ada produk dengan stok rendah")
        
        # Footer
        p.setFont("Helvetica-Oblique", 8)
        p.drawString(2*cm, 2*cm, f"Generated by Smartgement AI - {datetime.now().strftime('%Y')}")
        
        p.save()
        return buffer.getvalue()

report_service = ReportService()
